/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   auth-method-certificate.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html, css} from 'lit-element';

import {AuthMethodBase} from './auth-method-base.js';

import {ClientCertificatesConsumerMixin} from '@advanced-rest-client/client-certificates-consumer-mixin/client-certificates-consumer-mixin.js';

declare namespace UiElements {

  /**
   * The `<auth-method-certificate>` element renders a form with installed
   * in the application client certificates.
   * The user can select a certificate from the list. Produced settings contains
   * the ID of selected certificate.
   * The application should handle this information by it's own.
   *
   * ### Example
   *
   * ```html
   * <auth-method-certificate selected="DATA STORE ID"></auth-method-certificate>
   * ```
   *
   * This example will produce a form with prefilled username and passowrd with
   * value "test".
   */
  class AuthMethodCertificate extends AuthMethodBase {

    /**
     * The id of selected certificate.
     */
    selected: string|null|undefined;
    constructor(type: any);
    render(): any;

    /**
     * Restores settings from stored value.
     *
     * @param settings Object returned by `_getSettings()`
     */
    restore(settings: object|null): void;

    /**
     * Resets state of the form.
     */
    reset(): void;
    _attachListeners(node: any): void;
    _detachListeners(node: any): void;

    /**
     * Validates the form.
     *
     * @returns Validation result.
     */
    validate(): Boolean|null;

    /**
     * Creates a settings object with user provided data.
     *
     * @returns User provided data
     */
    getSettings(): object|null;

    /**
     * Handler to the `auth-settings-changed` event (fired by all auth panels).
     * If the event was fired by other element with the same method ttype
     * then the form will be updated to incomming values.
     * This helps to sync changes between elements in the same app.
     */
    _onAuthSettings(e: Event|null): void;
    _selectedHandler(e: any): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "auth-method-certificate": UiElements.AuthMethodCertificate;
  }
}
